# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c576c46d1719b428af41146c33ba8ba47cca351c0ccfb9f13f32742ee1027d479576b8462f477c69c81000ec48fe95a86e5cc9dca95b4f904951b55c362cc626

test:
  secret_key_base: 03c8023798aca1f15e71a74d5694124fae4fa2a493e6ccc7c282e04b5d98d3e7aad1cf7c2e5ef359fe8a843933fb206542ff57e2bbd928a769929f553f8cd6c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
